---
collections:
  - name: awx.awx
  - name: amazon.aws
  - name: azure.azcollection
  - name: theforeman.foreman
  - name: google.cloud
  - name: openstack.cloud
  - name: community.general
  - name: community.vmware
  - name: community.docker
  - name: ovirt.ovirt
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows
  - name: redhatinsights.insights
  - name: community.hashi_vault
  - name: lucasheld.uptime_kuma

  - name: community.general
  - name: kubernetes.core
  - name: community.kubernetes
  - name: ansible.netcommon